In [1]:
#ライブラリのインポート
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
% matplotlib inline

In [2]:
# データセットの読み込み
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

これはどのオブジェクトならできるの？⇨できない"

これもどのオブジェクトならできるの？

ここまではデータの観察だから別にいいのか、やろうと思ったらnp.array()とかに変えればいいのか

In [3]:
train_df.head()

MSSubClass  Neighborhood  OverallQual  YearBuilt  YearRemodAdd  MasVnrType  \
0        14.0          16.0          6.0       96.0          42.0         2.0   
1        11.0          20.0          5.0       70.0          31.0         1.0   
2        14.0          16.0          6.0       99.0          53.0         2.0   
3         9.0          17.0          6.0       31.0          16.0         1.0   
4        14.0          24.0          7.0       87.0          38.0         2.0   

   MasVnrArea  ExterQual  Foundation  BsmtQual    ...      FullBath  \
0       196.0        2.0         5.0       2.0    ...           2.0   
1         0.0        1.0         2.0       2.0    ...           2.0   
2       162.0        2.0         5.0       2.0    ...           2.0   
3         0.0        1.0         1.0       1.0    ...           0.0   
4       350.0        2.0         5.0       2.0    ...           2.0   

   KitchenQual  TotRmsAbvGrd  Fireplaces  GarageType  GarageYrBlt  \
0          2.0           7.0         0.0         4.0         84.0   
1          1.0           4.0         1.0         4.0         55.0   
2          2.0           4.0         1.0         4.0         89.0   
3          2.0           5.0         1.0         1.0         77.0   
4          2.0           8.0         1.0         4.0         76.0   

   GarageFinish  GarageCars  GarageArea  SalePrice  
0           1.0         2.0       548.0   208500.0  
1           1.0         2.0       460.0   181500.0  
2           1.0         2.0       608.0   223500.0  
3           0.0         4.0       642.0   140000.0  
4           1.0         4.0       836.0   250000.0  

[5 rows x 24 columns]

目的変数と説明変数混合されてるけどいいのか？いいんだよね、このあとconcat()するから

ここの次の段階の特徴量が多いので、locメソッドで一部の特徴量のみを選択っていうのは、自分でデータをみて勝手に5つくらい選んでいいってことだよね？

特徴量の数が多いので、locメソッドで一部の特徴量のみを選択する必要はない

In [ ]:
#　散布図行列を出力
# locメソッドで一部の特徴量だけをピックアップ
import seaborn as sns
sns.pairplot(train_df, size = 3.0)
plt.show()
#これは時間かかるからなし！

In [4]:
#相関係数行列を出力
#数値の羅列になるので見づらい
train_df.corr()

MSSubClass  Neighborhood  OverallQual  YearBuilt  YearRemodAdd  \
MSSubClass      1.000000      0.532233     0.471136   0.572252      0.415910   
Neighborhood    0.532233      1.000000     0.667647   0.683095      0.521638   
OverallQual     0.471136      0.667647     1.000000   0.665203      0.552825   
YearBuilt       0.572252      0.683095     0.665203   1.000000      0.652419   
YearRemodAdd    0.415910      0.521638     0.552825   0.652419      1.000000   
MasVnrType      0.246813      0.400196     0.449358   0.420443      0.310870   
MasVnrArea      0.212010      0.368029     0.410238   0.298983      0.193044   
ExterQual       0.393934      0.631870     0.726278   0.638206      0.570870   
Foundation      0.445768      0.576118     0.568969   0.699337      0.551916   
BsmtQual        0.423389      0.629227     0.644946   0.707715      0.545541   
TotalBsmtSF     0.291599      0.456092     0.537808   0.434021      0.328112   
HeatingQC       0.305789      0.420371     0.457083   0.479935      0.519679   
1stFlrSF        0.237884      0.405290     0.476224   0.349924      0.295100   
GrLivArea       0.347673      0.411751     0.593007   0.369635      0.325158   
FullBath        0.329673      0.513701     0.552153   0.555510      0.452501   
KitchenQual     0.391700      0.566358     0.673331   0.575836      0.611669   
TotRmsAbvGrd    0.253413      0.282979     0.423438   0.246057      0.217923   
Fireplaces      0.283353      0.315569     0.396765   0.214032      0.162493   
GarageType      0.510706      0.456575     0.420713   0.519992      0.387933   
GarageYrBlt     0.408647      0.579489     0.574261   0.768672      0.617250   
GarageFinish    0.438262      0.466576     0.491404   0.554784      0.446760   
GarageCars      0.397369      0.585252     0.628715   0.570728      0.433995   
GarageArea      0.387789      0.529629     0.562022   0.523139      0.390554   
SalePrice       0.476982      0.696882     0.790982   0.619545      0.535370   

              MasVnrType  MasVnrArea  ExterQual  Foundation  BsmtQual  \
MSSubClass      0.246813    0.212010   0.393934    0.445768  0.423389   
Neighborhood    0.400196    0.368029   0.631870    0.576118  0.629227   
OverallQual     0.449358    0.410238   0.726278    0.568969  0.644946   
YearBuilt       0.420443    0.298983   0.638206    0.699337  0.707715   
YearRemodAdd    0.310870    0.193044   0.570870    0.551916  0.545541   
MasVnrType      1.000000    0.579165   0.415825    0.310319  0.393052   
MasVnrArea      0.579165    1.000000   0.349637    0.209916  0.314065   
ExterQual       0.415825    0.349637   1.000000    0.597832  0.638241   
Foundation      0.310319    0.209916   0.597832    1.000000  0.621976   
BsmtQual        0.393052    0.314065   0.638241    0.621976  1.000000   
TotalBsmtSF     0.374961    0.362452   0.470580    0.357950  0.410438   
HeatingQC       0.245128    0.159256   0.520027    0.519447  0.410107   
1stFlrSF        0.343786    0.342160   0.397835    0.208966  0.362984   
GrLivArea       0.248026    0.389893   0.435986    0.282314  0.369656   
FullBath        0.305025    0.266274   0.497192    0.462312  0.523471   
KitchenQual     0.362377    0.285190   0.716122    0.533146  0.562345   
TotRmsAbvGrd    0.194912    0.280041   0.308004    0.180213  0.238832   
Fireplaces      0.199416    0.247906   0.249335    0.113338  0.227714   
GarageType      0.315218    0.221484   0.378696    0.401139  0.424760   
GarageYrBlt     0.343755    0.229848   0.590883    0.644742  0.642954   
GarageFinish    0.323321    0.251678   0.482143    0.487728  0.525068   
GarageCars      0.429343    0.404375   0.557218    0.458128  0.545306   
GarageArea      0.380290    0.372567   0.495778    0.398155  0.458693   
SalePrice       0.426997    0.475241   0.682639    0.505503  0.635361   

                ...      FullBath  KitchenQual  TotRmsAbvGrd  Fireplaces  \
MSSubClass      ...      0.329673     0.391700      0.253413    0.283353   
Neighborhood    ...      0.513701  

In [5]:
#相関係数のが大きいやつをみるためにsortする
train_df.corr().sort_values(by='SalePrice')

MSSubClass  Neighborhood  OverallQual  YearBuilt  YearRemodAdd  \
MasVnrType      0.246813      0.400196     0.449358   0.420443      0.310870   
HeatingQC       0.305789      0.420371     0.457083   0.479935      0.519679   
GarageType      0.510706      0.456575     0.420713   0.519992      0.387933   
Fireplaces      0.283353      0.315569     0.396765   0.214032      0.162493   
MasVnrArea      0.212010      0.368029     0.410238   0.298983      0.193044   
MSSubClass      1.000000      0.532233     0.471136   0.572252      0.415910   
GarageFinish    0.438262      0.466576     0.491404   0.554784      0.446760   
Foundation      0.445768      0.576118     0.568969   0.699337      0.551916   
YearRemodAdd    0.415910      0.521638     0.552825   0.652419      1.000000   
GarageYrBlt     0.408647      0.579489     0.574261   0.768672      0.617250   
TotRmsAbvGrd    0.253413      0.282979     0.423438   0.246057      0.217923   
FullBath        0.329673      0.513701     0.552153   0.555510      0.452501   
1stFlrSF        0.237884      0.405290     0.476224   0.349924      0.295100   
TotalBsmtSF     0.291599      0.456092     0.537808   0.434021      0.328112   
YearBuilt       0.572252      0.683095     0.665203   1.000000      0.652419   
GarageArea      0.387789      0.529629     0.562022   0.523139      0.390554   
BsmtQual        0.423389      0.629227     0.644946   0.707715      0.545541   
KitchenQual     0.391700      0.566358     0.673331   0.575836      0.611669   
ExterQual       0.393934      0.631870     0.726278   0.638206      0.570870   
GarageCars      0.397369      0.585252     0.628715   0.570728      0.433995   
Neighborhood    0.532233      1.000000     0.667647   0.683095      0.521638   
GrLivArea       0.347673      0.411751     0.593007   0.369635      0.325158   
OverallQual     0.471136      0.667647     1.000000   0.665203      0.552825   
SalePrice       0.476982      0.696882     0.790982   0.619545      0.535370   

              MasVnrType  MasVnrArea  ExterQual  Foundation  BsmtQual  \
MasVnrType      1.000000    0.579165   0.415825    0.310319  0.393052   
HeatingQC       0.245128    0.159256   0.520027    0.519447  0.410107   
GarageType      0.315218    0.221484   0.378696    0.401139  0.424760   
Fireplaces      0.199416    0.247906   0.249335    0.113338  0.227714   
MasVnrArea      0.579165    1.000000   0.349637    0.209916  0.314065   
MSSubClass      0.246813    0.212010   0.393934    0.445768  0.423389   
GarageFinish    0.323321    0.251678   0.482143    0.487728  0.525068   
Foundation      0.310319    0.209916   0.597832    1.000000  0.621976   
YearRemodAdd    0.310870    0.193044   0.570870    0.551916  0.545541   
GarageYrBlt     0.343755    0.229848   0.590883    0.644742  0.642954   
TotRmsAbvGrd    0.194912    0.280041   0.308004    0.180213  0.238832   
FullBath        0.305025    0.266274   0.497192    0.462312  0.523471   
1stFlrSF        0.343786    0.342160   0.397835    0.208966  0.362984   
TotalBsmtSF     0.374961    0.362452   0.470580    0.357950  0.410438   
YearBuilt       0.420443    0.298983   0.638206    0.699337  0.707715   
GarageArea      0.380290    0.372567   0.495778    0.398155  0.458693   
BsmtQual        0.393052    0.314065   0.638241    0.621976  1.000000   
KitchenQual     0.362377    0.285190   0.716122    0.533146  0.562345   
ExterQual       0.415825    0.349637   1.000000    0.597832  0.638241   
GarageCars      0.429343    0.404375   0.557218    0.458128  0.545306   
Neighborhood    0.400196    0.368029   0.631870    0.576118  0.629227   
GrLivArea       0.248026    0.389893   0.435986    0.282314  0.369656   
OverallQual     0.449358    0.410238   0.726278    0.568969  0.644946   
SalePrice       0.426997    0.475241   0.682639    0.505503  0.635361   

                ...      FullBath  KitchenQual  TotRmsAbvGrd  Fireplaces  \
MasVnrType      ...      0.305025     0.362377      0.194912    0.199416   
HeatingQC       ...      0.342358  

In [6]:
#0.68以上を5つでやってみる

In [7]:
# trainデータを用意
# DataFrameの.valuesメソッドでarrayに変換できます
X = train_df.loc[:,['OverallQual','GrLivArea','Neighborhood','GarageCars','ExterQual']]

In [1]:
X.head()

NameError: name 'X' is not defined

In [9]:
#　testデータを用意
#DataFrameの.valuesメソッドでarrayに変換できます
y = train_df.loc[:,['SalePrice']].values

In [10]:
#どのように入っているか、最初の10個を表示して確認
y[:10]

array([[ 208500.],
       [ 181500.],
       [ 223500.],
       [ 140000.],
       [ 250000.],
       [ 143000.],
       [ 307000.],
       [ 200000.],
       [ 129900.],
       [ 118000.]])

In [11]:
#ホールド・アウト法によるデータの分割
#(X,y,テストにどの割合を割くか、分裂のしかたを決める乱数生成機)
#テストデータの割合は、test_size引数に指定することで変更可能です(今回は、train:test = 7:3)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [12]:
#データのサンプル数を確認する
print(X.shape)
print(y.shape)

(1460, 5)
(1460, 1)


In [13]:
# trainデータのサンプル数を確認する
print(X_train.shape)
print(y_train.shape)

(1022, 5)
(1022, 1)


In [14]:
#testデータのサンプル数を確認する
print(X_test.shape)
print(y_test.shape)

(438, 5)
(438, 1)


In [15]:
# 重回帰の線形回帰を実行
from sklearn.linear_model import LinearRegression
Ir = LinearRegression()

In [16]:
#　重回帰線形モデルの学習する
# trainデータのみを用いていることに注意！
Ir.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
# 定数項を出力する
Ir.intercept_

array([-51961.50536969])

In [18]:
#偏回帰係数を出力する
#[LSTATの係数、RMの係数]
Ir.coef_

array([[ 13758.15457159,     53.28877666,   2606.57872852,  14148.82900947,
         17200.18383748]])

In [19]:
print('モデルの性能評価')

モデルの性能評価


In [20]:
#決定係数をtrainとtestに分けて出力
#　過学習しているかどうかを確認
print('R^2')
print('train: %.3f' % Ir.score(X_train,y_train))
print('test: %.3f' % Ir.score(X_test,y_test))

R^2
train: 0.799
test: 0.766


In [21]:
# 自由度調整済み決定係数
# (決定係数, trainまたはtestのサンプル数, 利用した特徴量の数)
def adjusted(score, n_sample, n_features):
    adjusted_score = 1 - (1 - score) * ((n_sample - 1) / (n_sample - n_features - 1))
    return adjusted_score

In [22]:
# 自由度調整済み決定係数を出力
print('adjusted R^2')
print('train: %3f' % adjusted(Ir.score(X_train, y_train), len(y_train), 2))
print('test : %3f' % adjusted(Ir.score(X_test, y_test), len(y_test), 2))

adjusted R^2
train: 0.798292
test : 0.765036


前回は自動調節済み決定係数0.5ぐらいだったけど、進歩

In [23]:
# MSEを出力する関数を読み込む
from sklearn.metrics import mean_squared_error as mse

# RMSEをtrainとtestに分けて出力
# 過学習をしているかどうかを確認
print('RMSE')
print('train: %.3f' % (mse(y_train, Ir.predict(X_train)) ** 1/2))
print('test : %.3f' % (mse(y_test, Ir.predict(X_test)) ** 1/2))

RMSE
train: 613981234.971
test : 793933693.151


In [24]:
# trainデータを用意
# DataFrameの.valuesメソッドでarrayに変換できます
#一個減らしてもやってみる
X = train_df.loc[:,['OverallQual','GrLivArea','Neighborhood','GarageCars']]

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)
Ir.fit(X_train,y_train)
print('R^2')
print('train: %.3f' % Ir.score(X_train,y_train))
print('test: %.3f' % Ir.score(X_test,y_test))
def adjusted(score, n_sample, n_features):
    adjusted_score = 1 - (1 - score) * ((n_sample - 1) / (n_sample - n_features - 1))
    return adjusted_score
print('adjusted R^2')
print('train: %3f' % adjusted(Ir.score(X_train, y_train), len(y_train), 2))
print('test : %3f' % adjusted(Ir.score(X_test, y_test), len(y_test), 2))

R^2
train: 0.792
test: 0.761
adjusted R^2
train: 0.791324
test : 0.760000


下がったので、さっきのでOK.